# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '989ec61b-29e4-4bd1-842f-a45d2993e53a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RM1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'ARMDEVOPS/ST1.json'
    csmParametersFile: 'ARMDEVOPS/parameters.json'
    overrideParameters: '-projectName TESTI -linkedTemplateUri https://raw.githubusercontent.com/azdemmo/ARMDEVOPS/master/ST1.json'
    deploymentMode: 'Incremental'
